---
# tasks file for jenkins
- name: Install jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: https://pkg.jenkins.io/redhat
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    gpgcheck: yes

- name: install epel repo
  yum:
    name: epel-release

- name: install java openjdk
  yum:
    name: java-1.8.0-openjdk
    state: latest
    update_cache: yes

- name: install jenkins
  yum:
    name: jenkins
    state: latest
    update_cache: yes

- name: enable and start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: generate ssh keys for user jenkins
  user:
    name: jenkins
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: jenkins
    shell: /bin/bash

- name: copy ansible defaults values
  copy:
    src: files/.ansible.cfg
    dest: /var/lib/jenkins/.ansible.cfg
    owner: jenkins
    group: jenkins 
