---
# tasks file for jenkins
- name: Install jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: https://pkg.jenkins.io/redhat
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    gpgcheck: yes

- name: install epel repo
  yum:
    name: epel-release

- name: install java openjdk
  yum:
    name: java-1.8.0-openjdk
    state: latest
    update_cache: yes

- name: install jenkins
  yum:
    name: jenkins
    state: latest
    update_cache: yes

- name: enable and start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

